### ISSUE TITLE
cmake error  for mac 

### ISSUE THREAD

**Issue by 15189611** [weizongwei5/Obfuscator-LLVM-4.0-BUILD-NDK#1]
当我clone 下来后，然后创建文件夹build后。执行 cmake -DCMAKE_BUILD_TYPE=Release ../obfuscator/ 
报错说command not found

**Comment by BruceWind** [comment]
I think "command not found" is not my fault.

**Comment by BruceWind** [comment]
you could try this before you building.
```
  - brew update
  - brew install cmake
```

**Comment by BruceWind** [comment]
Im going to close this issue.sorry.
